[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy.cfg"
keys = [
    "/haproxy/backends",
    "/haproxy/hosts",
]
reload_cmd = "/usr/local/sbin/haproxy -f /etc/haproxy.cfg -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)"
